### PR TITLE
Remove INTEL from Demo Message

### PR DESCRIPTION
**Pull request by danintel**
Change INTEL TRUSTED COMPUTE FRAMEWORK (TCF)
to     TRUSTED COMPUTE FRAMEWORK (TCF)

Signed-off-by: danintel <daniel.anderson@intel.com>

### CODE REVIEW

**Comment by manju956** [comment]
> Change INTEL TRUSTED COMPUTE FRAMEWORK (TCF)
> to TRUSTED COMPUTE FRAMEWORK (TCF)
> 
> Signed-off-by: danintel [daniel.anderson@intel.com](mailto:daniel.anderson@intel.com)

Demo.py has reference to INTEL TRUSTED COMPUTE FRAMEWORK. Can you remove it?

**Comment by danintel** [comment]
@manju956 
I missed that one.  I removed INTEL from `tests/Demo.py`. Thanks.

**Comment by manju956** [comment]
> @manju956
> I missed that one. I removed INTEL from `tests/Demo.py`. Thanks.

I don't see Demo.py in files changed. Is it missed out?

**Comment by danintel** [comment]
@manju956  Try again. My previous push must have failed.

**Pull request merged**
